[package]
name = "day_13"
version = "0.1.0"
authors = ["JohnKossa <kg959ster@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
scan_fmt = "0.2.6"
enum_variant_type = "0.3.1"